routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::get('/dashboard', function () {
//    return view('dashboard');
//})->middleware(['auth'])->name('dashboard');
Route::get('/dashboard',  [DashboardController::class, 'index'])->name('dashboard');

Route::resource('app-admins', AdminController::class);
Route::resource('app-users', UserController::class);
Route::resource('projects', ProjectController::class);
Route::get('users', [AdminController::class, 'getAdminUsers'])->name('users');
Route::get('user', [UserController::class, 'getAdminUsers'])->name('user');

Route::get('project', [ProjectController::class, 'getAdminUsers'])->name('project');

Route::get('my-projects/{id}', [UserController::class, 'MyProjects'])->name('my-projects');
//my project
Route::get('project-user/{id}', [ProjectController::class, 'getUserProject'])->name('project-user');

require __DIR__.'/auth.php';

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    use HasFactory;
    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'description',
        'image',
        'video',
        'document',
        'user_id',
        'link',
        'status_id',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use App\Models\Status;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Crypt;
use PharIo\Manifest\Author;
use Yajra\DataTables\Facades\DataTables;

class ProjectController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('projects.index');
    }
    /**
     * Get Users DataTable
     *
     * @return \Illuminate\Http\Response
     */
    public function getAdminUsers()
    {
        $user = Auth::user();
        if ($user->hasRole(['user'])) {
            $users = Project::where('user_id',$user->id)->get();
            return Datatables::of($users)
                ->addColumn('user', function ($users){
                    return $users->user->name;
                })
                ->addColumn('action', function ($users) {
                    return '<div class="dropdown dropdown-inline">
								<a href="" class="btn btn-sm btn-clean btn-icon" data-toggle="dropdown">
	                                <i class="la la-cog"></i>
	                            </a>
							  	<div class="dropdown-menu dropdown-menu-sm dropdown-menu-right">
									<ul class="nav nav-hoverable flex-column">
							    		<li class="nav-item"><a class="nav-link" href="'.route('projects.show',$users->id).'"><i class="nav-icon la la-user"></i><span class="nav-text">View Project</span></a></li>
							    		<li class="nav-item"><a class="nav-link" href="'.route('projects.edit',$users->id).'"><i class="nav-icon la la-user"></i><span class="nav-text">Edit Project</span></a></li>
							    	</ul>
							  	</div>
							</div>

						';
                })
                ->rawColumns(['user', 'action'])
                ->make(true);
        }
        else{

        $users = Project::all();
        //  return $users->roles->first()->name;
        return Datatables::of($users)
            ->addColumn('user', function ($users){
                return $users->user->name;
            })
            ->addColumn('action', function ($users) {
                return '<div class="dropdown dropdown-inline">
								<a href="" class="btn btn-sm btn-clean btn-icon" data-toggle="dropdown">
	                                <i class="la la-cog"></i>
	                            </a>
							  	<div class="dropdown-menu dropdown-menu-sm dropdown-menu-right">
									<ul class="nav nav-hoverable flex-column">
							    		<li class="nav-item"><a class="nav-link" href="'.route('projects.show',$users->id).'"><i class="nav-icon la la-user"></i><span class="nav-text">View Project</span></a></li>
							    		<li class="nav-item"><a class="nav-link" href="'.route('projects.edit',$users->id).'"><i class="nav-icon la la-user"></i><span class="nav-text">Edit Project</span></a></li>
							    		<li class="nav-item"><a class="nav-link" href="'.route('projects.destroy',$users->id).'"><i class="nav-icon la la-user"></i><span class="nav-text">Delete Project</span></a></li>
							    	</ul>
							  	</div>
							</div>

						';
            })
            ->rawColumns(['user', 'action'])
            ->make(true);
    }
    }
    public function getUserProject($id)
    {
       // $users =  User::with('roles')->get();
        $users = Project::where('user_id',$id)->get();
        //  return $users->roles->first()->name;
        return Datatables::of($users)
            ->addColumn('action', function ($users) {
                return '<div class="dropdown dropdown-inline">
								<a href="" class="btn btn-sm btn-clean btn-icon" data-toggle="dropdown">
	                                <i class="la la-cog"></i>
	                            </a>
							  	<div class="dropdown-menu dropdown-menu-sm dropdown-menu-right">
									<ul class="nav nav-hoverable flex-column">
							    		<li class="nav-item"><a class="nav-link" href="'.route('projects.show',$users->id).'"><i class="nav-icon la la-user"></i><span class="nav-text">View Project</span></a></li>
							    		<li class="nav-item"><a class="nav-link" href="'.route('projects.edit',$users->id).'"><i class="nav-icon la la-user"></i><span class="nav-text">Edit Project</span></a></li>
							    	</ul>
							  	</div>
							</div>

						';
            })
            ->rawColumns(['user', 'action'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $status = Status::query()->orderby("name","asc")->select('id','name')->get();
        return view('projects.create',compact('status'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'description' => 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'video' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'document' => 'required|mimes:csv,txt,xlx,xls,pdf|max:2048',
            'status_id' => 'required',
        ]);

        $input = $request->all();
        if ($image = $request->file('image')) {
            $destinationPath = 'image/';
            if(!is_dir($destinationPath)) {
                mkdir($destinationPath, 0755, true);
            }
            $profileImage = date('YmdHis') . "." . $image->getClientOriginalExtension();
            $image->move($destinationPath, $profileImage);
            $input['image'] = "$profileImage";
        }
        if ($image = $request->file('document')) {
            $destinationPath = 'document/';
            if(!is_dir($destinationPath)) {
                mkdir($destinationPath, 0755, true);
            }
            $profileImage = date('YmdHis') . "." . $image->getClientOriginalExtension();
            $image->move($destinationPath, $profileImage);
            $input['document'] = "$profileImage";
        }
        $input['user_id'] = Auth::user()->id;
        Project::create($input);
        return redirect()->route('projects.index')
            ->with('success','Product created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $status = Status::query()->orderby("name","asc")->select('id','name')->get();

        $project = Project::findOrFail($id);

        return view('projects.edit',compact('project','status'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'description' => 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'video' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'document' => 'required|mimes:csv,txt,xlx,xls,pdf|max:2048',
            'status_id' => 'required',
        ]);

        $input = $request->all();
        if ($image = $request->file('image')) {
            $destinationPath = 'image/';
            if(!is_dir($destinationPath)) {
                mkdir($destinationPath, 0755, true);
            }
            $profileImage = date('YmdHis') . "." . $image->getClientOriginalExtension();
            $image->move($destinationPath, $profileImage);
            $input['image'] = "$profileImage";
        }
        else{
            unset($input['image']);
        }
        if ($image = $request->file('document')) {
            $destinationPath = 'document/';
            if(!is_dir($destinationPath)) {
                mkdir($destinationPath, 0755, true);
            }
            $profileImage = date('YmdHis') . "." . $image->getClientOriginalExtension();
            $image->move($destinationPath, $profileImage);
            $input['document'] = "$profileImage";
        }
        else{
            unset($input['image']);
        }

        $project = Project::query()->findOrFail($id);
        $input['user_id'] = Auth::user()->id;
        $project->update($input);
        return redirect()->route('projects.index')
            ->with('success','Project Updated created successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy( $id)
    {
        $project = Project::where('id', '=', $id)->firstOrFail();
        $project->delete();
        return redirect()->route('projects.index')
            ->with('success','Project deleted successfully');
    }
}

resources/views/projects/create.blade.php
@extends('layout.master')
@section('content')
    <div class="row" style="margin-top: -5%;">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('projects.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('projects.store') }}" method="POST" enctype="multipart/form-data">
        @csrf

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Description:</strong>
                    <textarea class="form-control" style="height:80px" name="description" placeholder="Description"></textarea>
                </div>
                <div class="form-group">
                    <strong>Link:</strong>
                    <input type="text" name="link" class="form-control" placeholder="Link">
                </div>
                <div class="form-group">
                    <strong>Status:</strong>
                    <select name="status_id" class="form-control">
                        <option selected disabled value="" >-- Select Status --</option>
                        <!-- Read Departments -->
                        @foreach($status as $main)
                            <option value='{{ $main->id }}'>{{ $main->name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Image:</strong>
                    <input type="file" name="image" class="form-control" placeholder="image">
                </div>
                <div class="form-group">
                    <strong>Document:</strong>
                    <input type="file" name="document" class="form-control" placeholder="Document">
                </div>
                <div class="form-group">
                    <strong>Video:</strong>
                    <input type="file" name="video" class="form-control" placeholder="Video">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
@endsection
@section('scripts')

@endsection

resources/views/projects/edit.blade.php
@extends('layout.master')
@section('content')
    <div class="row" style="margin-top: -5%;">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('projects.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('projects.update',$project->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        {{ method_field('PUT') }})
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name"  value="{{ $project->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Description:</strong>
                    <input class="form-control" style="height:80px" value="{{ $project->description }}" name="description" placeholder="Description"/>
                </div>
                <div class="form-group">
                    <strong>Link:</strong>
                    <input type="text" name="link" value="{{ $project->link }}" class="form-control" placeholder="Link">
                </div>
                <div class="form-group">
                    <strong>Status:</strong>
                    <select name="status_id" class="form-control">
                        <option selected disabled value="" >-- Select Status --</option>
                        <!-- Read Departments -->
                        @foreach($status as $main)
                            <option value='{{ $main->id }}'>{{ $main->name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Image:</strong>
                    <input type="file" name="image" value="{{ $project->image }}" class="form-control" placeholder="image">
                </div>
                <div class="form-group">
                    <strong>Document:</strong>
                    <input type="file" name="document" value="{{ $project->document }}" class="form-control" placeholder="Document">
                </div>
                <div class="form-group">
                    <strong>Video:</strong>
                    <input type="file" name="video" value="{{ $project->video }}"class="form-control" placeholder="Video">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
@endsection
@section('scripts')

@endsection

resources/views/projects/index-user-project.blade.php
@extends('layout.master')
@section('content')
    <!--end::Notice-->
    <!--begin::Card-->
    <div class="card card-custom" style="margin-top: -5%;">
        <div class="card-header flex-wrap border-0 pt-6 pb-0">
            <div class="card-title">
                <h3 class="card-label">My Projects
                </h3>
            </div>
            <div class="card-toolbar">
                <!--begin::Button-->
                <a href="{{ route('projects.create') }}" type="button" class="btn btn-primary font-weight-bolder">
                        <span class="svg-icon svg-icon-md">
                        <!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                <rect x="0" y="0" width="24" height="24" />
                                <circle fill="#000000" cx="9" cy="15" r="6" />
                                <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3" />
                            </g>
                        </svg>
                            <!--end::Svg Icon-->
                    </span>Register New Project
                </a>
                <!--end::Button-->
            </div>
        </div>
        <div class="card-body">
            <!--begin: Datatable-->
            <table class="table table-bordered table-hover table-checkable mt-10 datatable" id="kt_datatable" style="margin-top: 13px !important">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Image</th>
                    <th>Description</th>
                    <th>Document</th>
                    <th>Video</th>
                    <th>Link </th>
                    <th>Status </th>
                    <th>Action </th>
                </tr>
                </thead>
            </table>
            <!--end: Datatable-->
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        'use strict';
        var KTDatatablesDataSourceAjaxClient = function() {

            var initTable1 = function() {
                var table = $('#kt_datatable');

                // begin first table
                table.DataTable({
                    responsive: true,
                    stateSave: true,
                    "bDestroy": true,
                    dom: 'Bfrtip',
                    buttons: [{extend: 'copyHtml5'}, {
                        extend: 'excelHtml5',
                        exportOptions: {columns: ':visible'},
                    },
                        {
                            extend: 'pdfHtml5',
                            exportOptions: {columns: ':visible'},
                            orientation: 'landscape',
                            pageSize: 'TABLOID'
                        },
                        'colvis','pageLength'],
                    ajax: {
                        url: '{{route('user-projects', $user_id)}}',
                        type: 'GET',
                        data: {
                            pagination: {
                                perpage: 50,
                            },
                        },
                    },
                    columns: [
                        {data: 'id', name: 'id'},
                        {data: 'name', name: 'name'},
                        {data: 'image', name: 'image'},
                        {data: 'description', name: 'description'},
                        {data: 'document', name: 'document'},
                        {data: 'video', name: 'video'},
                        {data: 'link', name: 'link'},
                        {data: 'status_id', name: 'status_id'},
                        {data: 'action', name: 'action'},
                    ],
                    columnDefs: [
                        {
                            width: '75px',
                            targets: -2,
                            render: function(data, type, full, meta) {
                                var is_active = {
                                    1: {'title': 'Active', 'state': 'danger'},
                                    2: {'title': 'Incomplete', 'state': 'primary'},
                                    3: {'title': 'Ongoing ', 'state': 'success'},
                                    4: {'title': 'Stuck ', 'state': 'success'},
                                };

                                if (typeof is_active[data] === 'undefined') {
                                    return data;
                                }
                                return '<span class="label label-' + is_active[data].state + ' label-dot mr-2"></span>' +
                                    '<span class="font-weight-bold text-' + is_active[data].state + '">' + is_active[data].title + '</span>';
                            },
                        },
                    ],
                });
            };

            return {

                //main function to initiate the module
                init: function() {
                    initTable1();
                },

            };

        }();

        jQuery(document).ready(function() {
            KTDatatablesDataSourceAjaxClient.init();
        });

    </script>
@endsection

resources/views/projects/index.blade.php
@extends('layout.master')
@section('content')
    <!--end::Notice-->
    <!--begin::Card-->
    <div class="card card-custom" style="margin-top: -5%;">
        <div class="card-header flex-wrap border-0 pt-6 pb-0">
            <div class="card-title">
                <h3 class="card-label">Registered System Projects
                </h3>
            </div>
            <div class="card-toolbar">
                <!--begin::Button-->
                <a href="{{ route('projects.create') }}" type="button" class="btn btn-primary font-weight-bolder">
                        <span class="svg-icon svg-icon-md">
                        <!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                <rect x="0" y="0" width="24" height="24" />
                                <circle fill="#000000" cx="9" cy="15" r="6" />
                                <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3" />
                            </g>
                        </svg>
                            <!--end::Svg Icon-->
                    </span>Register New Project
                </a>
                <!--end::Button-->
            </div>
        </div>
        <div class="card-body">
            <!--begin: Datatable-->
            <table class="table table-bordered table-hover table-checkable mt-10 datatable" id="kt_datatable" style="margin-top: 13px !important">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Image</th>
                    <th>Description</th>
                    <th>Document</th>
                    <th>Video</th>
                    <th>User</th>
                    <th>Link </th>
                    <th>Status </th>
                    <th>Action </th>
                </tr>
                </thead>
            </table>
            <!--end: Datatable-->
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        'use strict';
        var KTDatatablesDataSourceAjaxClient = function() {

            var initTable1 = function() {
                var table = $('#kt_datatable');

                // begin first table
                table.DataTable({
                    responsive: true,
                    stateSave: true,
                    "bDestroy": true,
                    dom: 'Bfrtip',
                    buttons: [{extend: 'copyHtml5'}, {
                        extend: 'excelHtml5',
                        exportOptions: {columns: ':visible'},
                    },
                        {
                            extend: 'pdfHtml5',
                            exportOptions: {columns: ':visible'},
                            orientation: 'landscape',
                            pageSize: 'TABLOID'
                        },
                        'colvis','pageLength'],
                    ajax: {
                        url: '{!! route('project') !!}',

                        type: 'GET',
                        data: {
                            pagination: {
                                perpage: 50,
                            },
                        },
                    },
                    columns: [
                        {data: 'id', name: 'id'},
                        {data: 'name', name: 'name'},
                        {data: 'image', name: 'image'},
                        {data: 'description', name: 'description'},
                        {data: 'document', name: 'document'},
                        {data: 'video', name: 'video'},
                        {data: 'user', name: 'user'},
                        {data: 'link', name: 'link'},
                        {data: 'status_id', name: 'status_id'},
                        {data: 'action', name: 'action'},
                    ],
                    columnDefs: [
                        {
                            width: '75px',
                            targets: -2,
                            render: function(data, type, full, meta) {
                                var is_active = {
                                    1: {'title': 'Active', 'state': 'danger'},
                                    2: {'title': 'Incomplete', 'state': 'primary'},
                                    3: {'title': 'Ongoing ', 'state': 'success'},
                                    4: {'title': 'Stuck ', 'state': 'success'},
                                };

                                if (typeof is_active[data] === 'undefined') {
                                    return data;
                                }
                                return '<span class="label label-' + is_active[data].state + ' label-dot mr-2"></span>' +
                                    '<span class="font-weight-bold text-' + is_active[data].state + '">' + is_active[data].title + '</span>';
                            },
                        },
                    ],
                });
            };

            return {

                //main function to initiate the module
                init: function() {
                    initTable1();
                },

            };

        }();

        jQuery(document).ready(function() {
            KTDatatablesDataSourceAjaxClient.init();
        });

    </script>
@endsection